use_frameworks!

platform :ios, '8.0'

target 'DeviceOrientationManager_Example' do
  pod 'DeviceOrientationManager', :path => '../'

  target 'DeviceOrientationManager_Tests' do
    inherit! :search_paths

    
  end
end
